## modify accordingly
name: Project Name
description: Project Description

## uncomment when importing the theme
#remote_theme: forsyde/forsyde-web-theme

## uncomment *only* if this is a project page.
#parent-url: https://forsyde.github.io

## uncomment and modify accordingly to override the defaults
#maintainer:
#- name: <maintainer>
#- url: https://github.com/<maintainer>

## uncomment and modify accordingly *only* if this is a project page.
#github-releases:
#- zip_url: https://api.github.com/repos/forsyde/<proj>/zipball/master
#- tar_url: https://api.github.com/repos/forsyde/<proj>/tarball/master

## paths to exclude from the site generation
exclude: [docs, Gemfile.lock, Gemfile]

## uncomment the line below when on a project page
plugins:
- jekyll-seo-tag
- jekyll-sitemap
#- jekyll-remote-theme
